name: ssg_smart2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+16

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  provider: ^6.1.2
  #connectivity: ^3.0.3
  connectivity_plus: ^6.0.5
  webview_flutter: ^4.9.0
  dio: ^5.6.0
  http: ^1.4.0
  oauth2: ^2.0.0
  freezed: ^3.0.6
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.2.4
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  photo_view: ^0.15.0
  package_info_plus: ^8.3.0
  universal_platform: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  intl: ^0.17.0


  #firebase_core: ^2.13.0
  #firebase_messaging: ^14.7.3
  #flutter_local_notifications: ^17.2.2
  #navigation_history_observer: ^1.1.0
  #firebase_core_platform_interface: ^5.4.0

  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  #flutter_local_notifications: ^19.2.1
  navigation_history_observer: ^1.1.0
  firebase_core_platform_interface: ^5.0.0

  flutter_svg: any
  flutter_html: any
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.3.1
  #flutter_google_places: ^0.3.0
  geocoding: any
  geolocator: ^14.0.2
  geolocator_android: ^5.0.2
  flutter_typeahead: ^5.2.0
  flutter_datetime_picker_plus: ^2.2.0
  dropdown_button2: ^2.3.9
  flutter_slidable: ^4.0.0
  floating_bubbles: ^2.6.2
  path_provider: ^2.1.4
  permission_handler: ^12.0.0+1
  flutter_downloader: ^1.11.8
  device_info_plus: any
  share_plus: ^11.0.0
  charts_flutter: ^0.12.0
  uuid: any
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  flutter_polyline_points: ^2.1.0
  text_divider: ^1.0.0
#  simple_barcode_scanner: ^0.1.1
  badges: ^3.1.2
  toggle_switch: ^2.3.0
  pdf: ^3.11.1
  printing: ^5.13.1
  open_file: ^3.3.1
  flutter_pdfview: ^1.3.4
  flutter_launcher_icons: ^0.14.4
  flutter_image_compress: ^2.4.0
  #flutter_native_image: ^0.0.6+1
  horizontal_data_table: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "icons/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/


  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700